In [1]:
from google.colab import drive
drive.mount('/content/ecommerce_project/')

Mounted at /content/ecommerce_project/

In [2]:
import pandas as pd
data_path = "/content/ecommerce_project/MyDrive/ecommerce_project/"

orders      = pd.read_csv(data_path + "olist_orders_dataset.csv")
order_items = pd.read_csv(data_path + "olist_order_items_dataset.csv")
customers   = pd.read_csv(data_path + "olist_customers_dataset.csv")
products    = pd.read_csv(data_path + "olist_products_dataset.csv")
sellers     = pd.read_csv(data_path + "olist_sellers_dataset.csv")
payments    = pd.read_csv(data_path + "olist_order_payments_dataset.csv")
reviews     = pd.read_csv(data_path + "olist_order_reviews_dataset.csv")
geolocation = pd.read_csv(data_path + "olist_geolocation_dataset.csv")

print("✅ All files loaded successfully!")

✅ All files loaded successfully!

In [3]:
orders.head()

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13 00:00:00
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04 00:00:00
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15 00:00:00
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26 00:00:00

In [4]:
orders.shape

(99441, 8)

In [5]:
orders.dtypes

order_id                         object
customer_id                      object
order_status                     object
order_purchase_timestamp         object
order_approved_at                object
order_delivered_carrier_date     object
order_delivered_customer_date    object
order_estimated_delivery_date    object
dtype: object

In [6]:
orders.isnull().sum()

order_id                            0
customer_id                         0
order_status                        0
order_purchase_timestamp            0
order_approved_at                 160
order_delivered_carrier_date     1783
order_delivered_customer_date    2965
order_estimated_delivery_date       0
dtype: int64

In [7]:
orders['order_status'].value_counts()

order_status
delivered      96478
shipped         1107
canceled         625
unavailable      609
invoiced         314
processing       301
created            5
approved           2
Name: count, dtype: int64

In [8]:
orders.duplicated().sum()

np.int64(0)

In [9]:
customers.head()

,customer_id,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state
0,06b8999e2fba1a1fbc88172c00ba8bc7,861eff4711a542e4b93843c6dd7febb0,14409,franca,SP
1,18955e83d337fd6b2def6b18a428ac77,290c77bc529b7ac935b93aa66c333dc3,9790,sao bernardo do campo,SP
2,4e7b3e00288586ebd08712fdd0374a03,060e732b5b29e8181a18229c7b0b2b5e,1151,sao paulo,SP
3,b2b6027bc5c5109e529d4dc6358b12c3,259dac757896d24d7702b9acbbff3f3c,8775,mogi das cruzes,SP
4,4f2d8ab171c80ec8364f7c12e35b23ad,345ecd01c38d18a9036ed96c73b8d066,13056,campinas,SP

In [10]:
customers.shape

(99441, 5)

In [11]:
print("total customer records:" ,customers['customer_id'].nunique())
print("total unique customer :", customers['customer_unique_id'].nunique())

total customer records: 99441
total unique customer : 96096

In [12]:
customers.dtypes

customer_id                 object
customer_unique_id          object
customer_zip_code_prefix     int64
customer_city               object
customer_state              object
dtype: object

In [13]:
customers.isnull().sum()

customer_id                 0
customer_unique_id          0
customer_zip_code_prefix    0
customer_city               0
customer_state              0
dtype: int64

In [14]:
print("Order_items",order_items.shape)
print("Customers",customers.shape)
print("Products",products.shape)
print("Sellers",sellers.shape)
print("payment",payments.shape)
print("reviews",reviews.shape)
print("geolocation",geolocation.shape)

Order_items (112650, 7)
Customers (99441, 5)
Products (32951, 9)
Sellers (3095, 4)
payment (103886, 5)
reviews (99224, 7)
geolocation (1000163, 5)

In [15]:
print("order_items",order_items.dtypes)

order_items order_id                object
order_item_id            int64
product_id              object
seller_id               object
shipping_limit_date     object
price                  float64
freight_value          float64
dtype: object

In [16]:
order_items.head()

,order_id,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value
0,00010242fe8c5a6d1ba2dd792cb16214,1,4244733e06e7ecb4970a6e2683c13e61,48436dade18ac8b2bce089ec2a041202,2017-09-19 09:45:35,58.90,13.29
1,00018f77f2f0320c557190d7a144bdd3,1,e5f2d52b802189ee658865ca93d83a8f,dd7ddc04e1b6c2c614352b383efe2d36,2017-05-03 11:05:13,239.90,19.93
2,000229ec398224ef6ca0657da4fc703e,1,c777355d18b72b67abbeef9df44fd0fd,5b51032eddd242adc84c38acab88f23d,2018-01-18 14:48:30,199.00,17.87
3,00024acbcdf0a6daa1e931b038114c75,1,7634da152a4610f1595efa32f14722fc,9d7a1d34a5052409006425275ba1c2b4,2018-08-15 10:10:18,12.99,12.79
4,00042b26cf59d7ce69dfabb4e55b4fd9,1,ac6c3623068f30de03045865e4e10089,df560393f3a51e74553ab94004ba5c87,2017-02-13 13:57:51,199.90,18.14

In [17]:
order_items.isnull().sum()

order_id               0
order_item_id          0
product_id             0
seller_id              0
shipping_limit_date    0
price                  0
freight_value          0
dtype: int64

In [18]:
products.dtypes

product_id                     object
product_category_name          object
product_name_lenght           float64
product_description_lenght    float64
product_photos_qty            float64
product_weight_g              float64
product_length_cm             float64
product_height_cm             float64
product_width_cm              float64
dtype: object

In [19]:
products.head()

,product_id,product_category_name,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm
0,1e9e8ef04dbcff4541ed26657ea517e5,perfumaria,40.0,287.0,1.0,225.0,16.0,10.0,14.0
1,3aa071139cb16b67ca9e5dea641aaa2f,artes,44.0,276.0,1.0,1000.0,30.0,18.0,20.0
2,96bd76ec8810374ed1b65e291975717f,esporte_lazer,46.0,250.0,1.0,154.0,18.0,9.0,15.0
3,cef67bcfe19066a932b7673e239eb23d,bebes,27.0,261.0,1.0,371.0,26.0,4.0,26.0
4,9dc1a7de274444849c219cff195d0b71,utilidades_domesticas,37.0,402.0,4.0,625.0,20.0,17.0,13.0

In [20]:
products.isnull().sum()

product_id                      0
product_category_name         610
product_name_lenght           610
product_description_lenght    610
product_photos_qty            610
product_weight_g                2
product_length_cm               2
product_height_cm               2
product_width_cm                2
dtype: int64

In [21]:
sellers.dtypes

seller_id                 object
seller_zip_code_prefix     int64
seller_city               object
seller_state              object
dtype: object

In [22]:
sellers.head()

,seller_id,seller_zip_code_prefix,seller_city,seller_state
0,3442f8959a84dea7ee197c632cb2df15,13023,campinas,SP
1,d1b65fc7debc3361ea86b5f14c68d2e2,13844,mogi guacu,SP
2,ce3ad9de960102d0677a81f5d0bb7b2d,20031,rio de janeiro,RJ
3,c0f3eea2e14555b6faeea3dd58c1b1c3,4195,sao paulo,SP
4,51a04a8a6bdcb23deccc82b0b80742cf,12914,braganca paulista,SP

In [23]:
sellers.isnull().sum()

seller_id                 0
seller_zip_code_prefix    0
seller_city               0
seller_state              0
dtype: int64

In [24]:
payments.dtypes

order_id                 object
payment_sequential        int64
payment_type             object
payment_installments      int64
payment_value           float64
dtype: object

In [25]:
payments.isnull().sum()

order_id                0
payment_sequential      0
payment_type            0
payment_installments    0
payment_value           0
dtype: int64

In [26]:
payments.head()

,order_id,payment_sequential,payment_type,payment_installments,payment_value
0,b81ef226f3fe1789b1e8b2acac839d17,1,credit_card,8,99.33
1,a9810da82917af2d9aefd1278f1dcfa0,1,credit_card,1,24.39
2,25e8ea4e93396b6fa0d3dd708e76c1bd,1,credit_card,1,65.71
3,ba78997921bbcdc1373bb41e913ab953,1,credit_card,8,107.78
4,42fdf880ba16b47b59251dd489d4441a,1,credit_card,2,128.45

In [27]:
reviews.dtypes

review_id                  object
order_id                   object
review_score                int64
review_comment_title       object
review_comment_message     object
review_creation_date       object
review_answer_timestamp    object
dtype: object

In [28]:
reviews.isnull().sum()

review_id                      0
order_id                       0
review_score                   0
review_comment_title       87656
review_comment_message     58247
review_creation_date           0
review_answer_timestamp        0
dtype: int64

In [29]:
reviews.head()

,review_id,order_id,review_score,review_comment_title,review_comment_message,review_creation_date,review_answer_timestamp
0,7bc2406110b926393aa56f80a40eba40,73fc7af87114b39712e6da79b0a377eb,4,NaN,NaN,2018-01-18 00:00:00,2018-01-18 21:46:59
1,80e641a11e56f04c1ad469d5645fdfde,a548910a1c6147796b98fdf73dbeba33,5,NaN,NaN,2018-03-10 00:00:00,2018-03-11 03:05:13
2,228ce5500dc1d8e020d8d1322874b6f0,f9e4b658b201a9f2ecdecbb34bed034b,5,NaN,NaN,2018-02-17 00:00:00,2018-02-18 14:36:24
3,e64fb393e7b32834bb789ff8bb30750e,658677c97b385a9be170737859d3511b,5,NaN,Recebi bem antes do prazo estipulado.,2017-04-21 00:00:00,2017-04-21 22:02:06
4,f7c4243c7fe1938f181bec41a392bdeb,8e6bfb81e283fa7e4f11123a3fb894f1,5,NaN,Parabéns lojas lannister adorei comprar pela I...,2018-03-01 00:00:00,2018-03-02 10:26:53

In [30]:
reviews.shape

(99224, 7)

In [31]:
geolocation.shape

(1000163, 5)

In [32]:
geolocation.isnull().sum()

geolocation_zip_code_prefix    0
geolocation_lat                0
geolocation_lng                0
geolocation_city               0
geolocation_state              0
dtype: int64

In [33]:
geolocation.head()

,geolocation_zip_code_prefix,geolocation_lat,geolocation_lng,geolocation_city,geolocation_state
0,1037,-23.545621,-46.639292,sao paulo,SP
1,1046,-23.546081,-46.644820,sao paulo,SP
2,1046,-23.546129,-46.642951,sao paulo,SP
3,1041,-23.544392,-46.639499,sao paulo,SP
4,1035,-23.541578,-46.641607,sao paulo,SP

Step 2 — Data Cleaning & Transformation

In [34]:
orders.dtypes

order_id                         object
customer_id                      object
order_status                     object
order_purchase_timestamp         object
order_approved_at                object
order_delivered_carrier_date     object
order_delivered_customer_date    object
order_estimated_delivery_date    object
dtype: object

In [35]:
date_columns = [
    "order_purchase_timestamp",
    "order_approved_at",
    "order_delivered_carrier_date",
    "order_estimated_delivery_date",
    "order_delivered_customer_date"
]
for col in date_columns:
  orders[col] = pd.to_datetime(orders[col])

print("Date columns converted successfully..")

Date columns converted successfully..

In [36]:
orders.dtypes

order_id                                 object
customer_id                              object
order_status                             object
order_purchase_timestamp         datetime64[ns]
order_approved_at                datetime64[ns]
order_delivered_carrier_date     datetime64[ns]
order_delivered_customer_date    datetime64[ns]
order_estimated_delivery_date    datetime64[ns]
dtype: object

In [37]:
orders['delivery_time_days'] = (
    orders['order_delivered_customer_date'] - orders['order_purchase_timestamp']
).dt.days

In [38]:
print(orders['delivery_time_days'].describe())

count    96476.000000
mean        12.094086
std          9.551746
min          0.000000
25%          6.000000
50%         10.000000
75%         15.000000
max        209.000000
Name: delivery_time_days, dtype: float64

In [39]:
orders.isnull().sum()

order_id                            0
customer_id                         0
order_status                        0
order_purchase_timestamp            0
order_approved_at                 160
order_delivered_carrier_date     1783
order_delivered_customer_date    2965
order_estimated_delivery_date       0
delivery_time_days               2965
dtype: int64

In [40]:
orders.isnull().sum()[orders.isnull().sum()>0]

order_approved_at                 160
order_delivered_carrier_date     1783
order_delivered_customer_date    2965
delivery_time_days               2965
dtype: int64

In [41]:
orders['order_approved_at'] = orders['order_approved_at'].fillna(pd.NaT)
orders['order_delivered_carrier_date'] = orders['order_delivered_carrier_date'].fillna(pd.NaT)
orders['order_delivered_customer_date'] = orders['order_delivered_customer_date'].fillna(pd.NaT)

print("✅ Null values handled correctly!")

✅ Null values handled correctly!

In [42]:
orders['order_approved_at'].dtypes

dtype('<M8[ns]')

In [43]:
# Convert back to datetime properly
orders['order_approved_at'] = pd.to_datetime(orders['order_approved_at'], errors='coerce')

print(orders['order_approved_at'].dtype)

datetime64[ns]

In [44]:
print(orders['order_approved_at'].isnull().sum())

160

In [45]:
order_items.shape

order_items.isnull().sum()

order_id               0
order_item_id          0
product_id             0
seller_id              0
shipping_limit_date    0
price                  0
freight_value          0
dtype: int64

In [46]:
order_items.dtypes

order_id                object
order_item_id            int64
product_id              object
seller_id               object
shipping_limit_date     object
price                  float64
freight_value          float64
dtype: object

In [47]:
order_items.shape

(112650, 7)

In [48]:
order_items['shipping_limit_date'] = pd.to_datetime(order_items['shipping_limit_date'])

In [49]:
payments.isnull().sum()

order_id                0
payment_sequential      0
payment_type            0
payment_installments    0
payment_value           0
dtype: int64

In [50]:
payments.shape

(103886, 5)

In [51]:
payments.isnull().sum()

order_id                0
payment_sequential      0
payment_type            0
payment_installments    0
payment_value           0
dtype: int64

In [52]:
payments.dtypes

order_id                 object
payment_sequential        int64
payment_type             object
payment_installments      int64
payment_value           float64
dtype: object

In [53]:
print(payments['payment_type'].value_counts())

payment_type
credit_card    76795
boleto         19784
voucher         5775
debit_card      1529
not_defined        3
Name: count, dtype: int64

In [54]:
print(reviews.shape)
print(reviews.dtypes)
print(reviews.isnull().sum())

(99224, 7)
review_id                  object
order_id                   object
review_score                int64
review_comment_title       object
review_comment_message     object
review_creation_date       object
review_answer_timestamp    object
dtype: object
review_id                      0
order_id                       0
review_score                   0
review_comment_title       87656
review_comment_message     58247
review_creation_date           0
review_answer_timestamp        0
dtype: int64

In [55]:
reviews['review_comment_title'] = reviews['review_comment_title'].fillna('No_Title')
reviews['review_comment_message'] = reviews['review_comment_message'].fillna('No_comments')

In [56]:
reviews['review_creation_date']=pd.to_datetime(reviews['review_creation_date'])
reviews['review_answer_timestamp']=pd.to_datetime(reviews['review_answer_timestamp'])

In [57]:
reviews.isnull().sum()

review_id                  0
order_id                   0
review_score               0
review_comment_title       0
review_comment_message     0
review_creation_date       0
review_answer_timestamp    0
dtype: int64

In [58]:
print(products.shape)
print(products.dtypes)
print(products.isnull().sum())

(32951, 9)
product_id                     object
product_category_name          object
product_name_lenght           float64
product_description_lenght    float64
product_photos_qty            float64
product_weight_g              float64
product_length_cm             float64
product_height_cm             float64
product_width_cm              float64
dtype: object
product_id                      0
product_category_name         610
product_name_lenght           610
product_description_lenght    610
product_photos_qty            610
product_weight_g                2
product_length_cm               2
product_height_cm               2
product_width_cm                2
dtype: int64

In [59]:
# Fix null category name
products['product_category_name'] = products['product_category_name'].fillna('unknow')

In [60]:
# Fix 2 null rows in physical dimensions with median
products['product_weight_g'] = products['product_weight_g'].fillna(products['product_weight_g'].median())
products['product_length_cm'] = products['product_length_cm'].fillna(products['product_length_cm'].median())
products['product_height_cm'] = products['product_height_cm'].fillna(products['product_height_cm'].median())
products['product_width_cm'] = products['product_width_cm'].fillna(products['product_width_cm'].median())

In [61]:
products = products.rename(columns={
    'product_name_lenght': 'product_name_length',
    'product_description_lenght': 'product_description_length',
})

In [62]:
products.isnull().sum()

product_id                      0
product_category_name           0
product_name_length           610
product_description_length    610
product_photos_qty            610
product_weight_g                0
product_length_cm               0
product_height_cm               0
product_width_cm                0
dtype: int64

In [63]:
products['product_description_length'] = products['product_description_length'].fillna(products['product_description_length'].median())
products['product_name_length'] = products['product_name_length'].fillna(products['product_name_length'].median())
products['product_photos_qty'] = products['product_photos_qty'].fillna(products['product_photos_qty'].median())

In [64]:
products.isnull().sum()

product_id                    0
product_category_name         0
product_name_length           0
product_description_length    0
product_photos_qty            0
product_weight_g              0
product_length_cm             0
product_height_cm             0
product_width_cm              0
dtype: int64

In [65]:
print(customers.shape)
print(customers.dtypes)
print(customers.isnull().sum())

(99441, 5)
customer_id                 object
customer_unique_id          object
customer_zip_code_prefix     int64
customer_city               object
customer_state              object
dtype: object
customer_id                 0
customer_unique_id          0
customer_zip_code_prefix    0
customer_city               0
customer_state              0
dtype: int64

In [66]:
customers['customer_zip_code_prefix'] = customers['customer_zip_code_prefix'].astype(str)

In [67]:
print(sellers.shape)
print(sellers.dtypes)
print(sellers.isnull().sum())

(3095, 4)
seller_id                 object
seller_zip_code_prefix     int64
seller_city               object
seller_state              object
dtype: object
seller_id                 0
seller_zip_code_prefix    0
seller_city               0
seller_state              0
dtype: int64

In [68]:
sellers['seller_zip_code_prefix'] = sellers['seller_zip_code_prefix'].astype(str)

In [69]:
print(geolocation.shape)
print(geolocation.dtypes)
print(geolocation.isnull().sum())

(1000163, 5)
geolocation_zip_code_prefix      int64
geolocation_lat                float64
geolocation_lng                float64
geolocation_city                object
geolocation_state               object
dtype: object
geolocation_zip_code_prefix    0
geolocation_lat                0
geolocation_lng                0
geolocation_city               0
geolocation_state              0
dtype: int64

In [70]:
geolocation['geolocation_zip_code_prefix'] = geolocation['geolocation_zip_code_prefix'].astype(str)

In [71]:
geolocation = geolocation.drop_duplicates(subset='geolocation_zip_code_prefix')

In [72]:
geolocation.isnull().sum()

geolocation_zip_code_prefix    0
geolocation_lat                0
geolocation_lng                0
geolocation_city               0
geolocation_state              0
dtype: int64

In [73]:
geolocation.shape

(19015, 5)

In [74]:
pip install mysql-connector-python sqlalchemy pymysql

Collecting mysql-connector-python
  Downloading mysql_connector_python-9.6.0-cp312-cp312-manylinux_2_28_x86_64.whl.metadata (11 kB)
Requirement already satisfied: sqlalchemy in /usr/local/lib/python3.12/dist-packages (2.0.49)
Collecting pymysql
  Downloading pymysql-1.1.2-py3-none-any.whl.metadata (4.3 kB)
Requirement already satisfied: greenlet>=1 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy) (3.4.0)
Requirement already satisfied: typing-extensions>=4.6.0 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy) (4.15.0)
Downloading mysql_connector_python-9.6.0-cp312-cp312-manylinux_2_28_x86_64.whl (34.5 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 34.5/34.5 MB 52.4 MB/s eta 0:00:00
Downloading pymysql-1.1.2-py3-none-any.whl (45 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 45.3/45.3 kB 3.4 MB/s eta 0:00:00
Installing collected packages: pymysql, mysql-connector-python
Successfully installed mysql-connector-python-9.6.0 pymysql-1.1.2

In [75]:
translation = pd.read_csv(data_path + 'product_category_name_translation.csv')

In [76]:
print(translation.shape)
print(translation.dtypes)
print(translation.isnull().sum())

(71, 2)
product_category_name            object
product_category_name_english    object
dtype: object
product_category_name            0
product_category_name_english    0
dtype: int64

In [77]:
translation.head()

    product_category_name product_category_name_english
0            beleza_saude                 health_beauty
1  informatica_acessorios         computers_accessories
2              automotivo                          auto
3         cama_mesa_banho                bed_bath_table
4        moveis_decoracao               furniture_decor

In [78]:
# Merge translation into products table
products = products.merge(
    translation,
    on='product_category_name',
    how='left'
)

# Check result
print(products.shape)
print(products[['product_category_name', 'product_category_name_english']].head(10))

(32951, 10)
   product_category_name product_category_name_english
0             perfumaria                     perfumery
1                  artes                           art
2          esporte_lazer                sports_leisure
3                  bebes                          baby
4  utilidades_domesticas                    housewares
5  instrumentos_musicais           musical_instruments
6             cool_stuff                    cool_stuff
7       moveis_decoracao               furniture_decor
8       eletrodomesticos               home_appliances
9             brinquedos                          toys

In [79]:
print(products['product_category_name_english'].isnull().sum())

623

In [80]:
products['product_category_name_english'] = products['product_category_name_english'].fillna(products['product_category_name'])

In [81]:
orders.isnull().sum()

order_id                            0
customer_id                         0
order_status                        0
order_purchase_timestamp            0
order_approved_at                 160
order_delivered_carrier_date     1783
order_delivered_customer_date    2965
order_estimated_delivery_date       0
delivery_time_days               2965
dtype: int64

In [82]:
# Correct way to handle datetime null columns
orders['order_approved_at'] = orders['order_approved_at'].fillna(pd.NaT)
orders['order_delivered_carrier_date'] = orders['order_delivered_carrier_date'].fillna(pd.NaT)
orders['order_delivered_customer_date'] = orders['order_delivered_customer_date'].fillna(pd.NaT)

print("✅ Null values handled correctly!")

✅ Null values handled correctly!

In [83]:
orders['order_approved_at'].isnull().head(150)

0      False
1      False
2      False
3      False
4      False
       ...
145    False
146    False
147    False
148    False
149    False
Name: order_approved_at, Length: 150, dtype: bool

In [85]:
orders['order_delivered_customer_date'].dtypes

dtype('<M8[ns]')

In [86]:
orders['order_delivered_customer_date'].isnull().sum()

np.int64(2965)

In [87]:
orders['order_delivered_customer_date'] = orders['order_estimated_delivery_date'].fillna(pd.NaT)

In [88]:
orders['order_approved_at'].dtypes

dtype('<M8[ns]')

In [89]:
orders['order_approved_at'].isnull().sum()

np.int64(160)

In [90]:
orders['order_approved_at'] = orders['order_approved_at'].fillna(pd.NaT)

In [91]:
orders['order_delivered_carrier_date'].dtypes

dtype('<M8[ns]')

In [92]:
orders['order_delivered_carrier_date'].isnull().sum()

np.int64(1783)

In [93]:
orders['order_delivered_carrier_date'] = orders['order_delivered_carrier_date'].fillna(pd.NaT)

In [94]:
orders['delivery_time_days'].isnull().sum()

np.int64(2965)

In [95]:
orders['delivery_time_days'] = orders['delivery_time_days'].fillna(orders['delivery_time_days'].median())

In [ ]:
order_items['seller_id'].dtypes

In [97]:
sellers['seller_id'].dtypes

dtype('O')

In [100]:

output_path = "/content/ecommerce_project/MyDrive/ecommerce_project/cleaned/"

orders.to_csv(output_path + "cleaned_orders.csv", index=False)
order_items.to_csv(output_path + "cleaned_order_items.csv", index=False)
customers.to_csv(output_path + "cleaned_customers.csv", index=False)
products.to_csv(output_path + "cleaned_products.csv", index=False)
sellers.to_csv(output_path + "cleaned_sellers.csv", index=False)
payments.to_csv(output_path + "cleaned_payments.csv", index=False)
reviews.to_csv(output_path + "cleaned_reviews.csv", index=False)
geolocation.to_csv(output_path + "cleaned_geolocation.csv", index=False)